runtime: python311  # Указываем версию Python
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main_bot:app

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

network:
  session_affinity: true
